allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@clerk/localizations@4.20.0'
  - '@clerk/shared@4.36.0'
  - '@clerk/backend@3.20.1'
  - '@clerk/nextjs@7.9.7'
  - '@clerk/react@6.17.2'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
