// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const clerkAppearance: any = {
  variables: {
    colorPrimary: "#00d4a8",
    colorDanger: "#f87171",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-inter), Inter, system-ui, sans-serif",
  },
  elements: {
    rootBox: "w-full",
    card: "!bg-transparent !shadow-none !border-0 !p-6 w-full",
    cardBox: "!bg-transparent !shadow-none !border-0 w-full",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    socialButtonsBlockButton: "!bg-[#1a1d21] !border-[#2a2d33] !text-[#edf0f5]",
    alternativeMethodsBlockButton: "!bg-[#1a1d21] !border-[#2a2d33] !text-[#edf0f5] !font-normal",
    alternativeMethodsBlockButtonText: "!font-normal !text-[#edf0f5]",
    formFieldLabel: "!text-[#9ea3b0]",
    formFieldInput: "!bg-[#0b0d0f] !border-[#3a3f4a] !text-[#edf0f5] placeholder:!text-[#6b7280] focus:!border-[#00d4a8]",
    formFieldSuccessText: "!text-emerald-400",
    formFieldWarningText: "!text-amber-400",
    formFieldErrorText: "!text-red-400",
    formFieldHintText: "!text-[#9ea3b0]",
    formFieldAction: "!text-[#00d4a8]",
    formFieldRadioLabel: "!text-[#edf0f5]",
    formFieldRadioLabelTitle: "!text-[#edf0f5]",
    formFieldRadioInput: "!border-[#3a3f4a]",
    formButtonPrimary: "!bg-[#00d4a8] !text-[#052821] !shadow-none",
    dividerLine: "!bg-[#2a2d33]",
    dividerText: "!text-[#6b7280]",
    footerActionText: "!text-[#6b7280]",
    footerActionLink: "!text-[#00d4a8]",
    footer: "!bg-[#0e1012]",
    identityPreviewText: "!text-[#edf0f5]",
    identityPreviewEditButton: "!text-[#00d4a8]",
    formResendCodeLink: "!text-[#00d4a8]",
    otpCodeFieldInput: "!bg-[#1a1d21] !border-[#2a2d33] !text-[#edf0f5]",
    alert: "!bg-red-500/10 !border-red-500/20",
    alertText: "!text-red-400",
  },
};
